### ISSUE TITLE
iOS build failure

### ISSUE THREAD

**Issue by tmoller96** [zaai123/wifi_configuration_2#1]
When building it to iOS, i get the following error message:

 `
-> Fetching podspec for 'wifi_configuration_2' from '.symlinks/plugins/wifi_configuration_2/ios'
    [!] No podspec found for 'wifi_configuration_2' in '.symlinks/plugins/wifi_configuration_2/ios'
`

If using a local machine, the fix for the issue can be seen [here](https://github.com/CameronStuartSmith/flutter_lottie/issues/19). However, this is not possible when using CI/CD pipeline to build and publishing the flutter app, as the pipeline uses a virtual mac machine, which can't be accessed to fix the issue.

**Comment by zaai123** [comment]
Right now this package is only available for  Android. Sorry for
inconvenience

**Comment by tmoller96** [comment]
Yes, i know. As of now, i'm doin another flow for iOS, where i don't use
the package. But i can't even compile to iOS, because i'm including the
pacakge so i can use it for Android. I have to manualy change the naming of
the package, on my own machine, before i can compile. But this is not
possible when using a build pipeline.

I Hope that you can fix this, as it seems as a very easy naming convention
fix.

man. 2. nov. 2020 kl. 12.04 skrev zaai123 <notifications@github.com>:

> Right now this package is only available for Android. Sorry for
> inconvenience
>

**Comment by tmoller96** [comment]
This issue has nothing to do with the fact that the package itself doesn't work on iOS. This is an error caught when building the app, as the iOS podspec can't find  'wifi_configuration_2' in '.symlinks/plugins/wifi_configuration_2/ios, because of some error in the naming.

**Comment by tmoller96** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:3.0cm 2.0cm 3.0cm 2.0cm;}
div.WordSection1
	{page:WordSection1;}

**Comment by zaai123** [comment]
Hi @tmoller96 i have changed the name of file. I didn't tested it. If you want to give a try it will be great. Thanks closing now

**Comment by tmoller96** [comment]
Hi @zaai123 
When i run 'flutter pub get', i get the following error:

`Invalid plugin specification wifi_configuration_2.
Cannot find the 'flutter.plugin.platforms' key in the 'pubspec.yaml' file. An instruction to format the 'pubspec.yaml' can be found here: https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms
exit code 1`
