### ISSUE TITLE
Invalid plugin specification wifi_configuration_2

### ISSUE THREAD

**Issue by melaLetics** [zaai123/wifi_configuration_2#3]
I try to add this package to my flutter project following the installing steps. 
Running flutter pub get leads to that error message:

> Invalid plugin specification wifi_configuration_2.
> Cannot find the `flutter.plugin.platforms` key in the `pubspec.yaml` file. An instruction to format the `pubspec.yaml` can be found here: https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms
> exit code 1

After removing the "wifi_configuration_2: ^1.1.0" entry, all is fine again so I could exclude an error in pubspec.yaml.

**Comment by santhoshselvan** [comment]
Faced the same issue. Switched to version 1.0.9

**Comment by ruttario** [comment]
Getting the same error here. Also tried 1.0.9 and 1.0.8 to no avail. Meh. 👎

**Comment by alfaiz12** [comment]
> Faced the same issue. Switched to version 1.0.9

Does it work?? i mean i tried but using ssid and password its not connecting to wifi everytime it shows unable to connect.any solution?

**Comment by alfaiz12** [comment]
> I try to add this package to my flutter project following the installing steps.
> Running flutter pub get leads to that error message:
> 
> > Invalid plugin specification wifi_configuration_2.
> > Cannot find the `flutter.plugin.platforms` key in the `pubspec.yaml` file. An instruction to format the `pubspec.yaml` can be found here: https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms
> > exit code 1
> 
> After removing the "wifi_configuration_2: ^1.1.0" entry, all is fine again so I could exclude an error in pubspec.yaml.

hey did you got any solution for it?? i am also trying but giving same error.

**Comment by melaLetics** [comment]
I moved back to use wifi_configuration: ^1.2.1 in my pubspec.yaml :(

**Comment by mustafa-fahimi** [comment]
Same issue and still no solution

**Comment by AMMAR187** [comment]
In the pubspec.yaml file within the plugin folder add the following :


```
plugin:
    platforms:
      android:
        package: com.example.wifi_configuration
        pluginClass: WifiConfigurationPlugin
```

**Comment by zaai123** [comment]
Fixed this issue in the latest version
Closing now
