### ISSUE TITLE
Keep failing to successfully connect to wifi network

### ISSUE THREAD

**Issue by ruttario** [zaai123/wifi_configuration_2#6]
I've updated my app to use the latest version 1.1.2+1.
I've tried to connect to a couple of wifi networks and my app keeps failing to connect.
Does anyone have the same problem?

By the way, can anyone suggest any other package to use instead of this one?
(Sorry, but I've already lost hope in this one, especially when it was giving build error before this latest update.)
In my app, I want to achieve a couple of things:
1. List wifi networks in range
2. Connect to the select wifi network
I've also tried to find a tutorial to code it up myself, but haven't found any good one.
Can anyone share with me a good tutorial?

**Comment by zaai123** [comment]
Right now this function is not supported. You can't connect to a network using this plugin.
I will update this as soon as i could.
Closing now
